"use client";

import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Bell, CalendarDays, Check, ChevronDown, ChevronRight, CircleDollarSign, Clock3, Flame, Gauge, LayoutDashboard, MapPin, Menu, Search, ShieldCheck, Sparkles, Swords, Target, Trophy, Undo2, UserRound, UsersRound, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Toaster, toast } from "sonner";

type View = "dashboard" | "matches" | "requests" | "fixtures" | "teams" | "profile" | "scoring";
type MatchPost = { id: number; team: string; initials: string; color: string; skill: string; ground: string; area: string; date: string; time: string; overs: number; ball: string; cost: number; share: number; age: string; note: string; rating: number; played: number; wins: number; cancellations: number };

const posts: MatchPost[] = [
  { id: 1, team: "Deccan Strikers", initials: "DS", color: "#ff7849", skill: "Intermediate", ground: "Boundary Box Arena", area: "Gachibowli", date: "20 Sep", time: "6:30–9:30 AM", overs: 20, ball: "Tennis", cost: 5200, share: 2600, age: "18 min ago", note: "Competitive but friendly Sunday game. Please arrive 20 minutes early.", rating: 4.8, played: 38, wins: 23, cancellations: 2 },
  { id: 2, team: "Hitech Hurricanes", initials: "HH", color: "#8b5cf6", skill: "Advanced", ground: "The Pavilion", area: "Kondapur", date: "20 Sep", time: "3:00–6:00 PM", overs: 25, ball: "Leather", cost: 7600, share: 3800, age: "42 min ago", note: "Leather-ball match with umpires included. White kit preferred.", rating: 4.6, played: 54, wins: 31, cancellations: 3 },
  { id: 3, team: "Jubilee Jaguars", initials: "JJ", color: "#199d6d", skill: "Intermediate", ground: "Pitch Perfect", area: "Madhapur", date: "21 Sep", time: "7:00–10:00 AM", overs: 20, ball: "Tennis", cost: 4800, share: 2400, age: "1 hr ago", note: "New ball provided. Balanced side preferred.", rating: 4.9, played: 26, wins: 17, cancellations: 1 },
  { id: 4, team: "Secunderabad Sixers", initials: "SS", color: "#3178f6", skill: "Beginner", ground: "CricZone 2", area: "Kompally", date: "22 Sep", time: "5:30–8:30 PM", overs: 15, ball: "Tennis", cost: 4200, share: 2100, age: "2 hrs ago", note: "Friendly weekday game. Underarm throwdowns before the match.", rating: 4.5, played: 19, wins: 8, cancellations: 1 },
];
const nav = [
  { id: "dashboard", label: "Overview", icon: LayoutDashboard }, { id: "matches", label: "Find matches", icon: Search }, { id: "requests", label: "Requests", icon: Swords, badge: "2" }, { id: "fixtures", label: "Fixtures", icon: CalendarDays },
  { id: "teams", label: "My teams", icon: UsersRound }, { id: "profile", label: "My profile", icon: UserRound },
] as const;

const postSchema = z.object({ team: z.string().min(1), date: z.string().refine(v => new Date(`${v}T23:59:59`) >= new Date(), "Choose a future date"), startTime: z.string().min(1, "Required"), endTime: z.string().min(1, "Required"), ground: z.string().min(3, "Enter a ground"), area: z.string().min(2, "Enter an area"), overs: z.coerce.number().min(5).max(50), ballType: z.enum(["Tennis", "Leather"]), skill: z.enum(["Beginner", "Intermediate", "Advanced"]), cost: z.coerce.number().min(0), share: z.coerce.number().min(0), notes: z.string().max(240).optional() })
  .refine(d => d.endTime > d.startTime, { path: ["endTime"], message: "End time must be later" }).refine(d => d.share <= d.cost, { path: ["share"], message: "Share cannot exceed total cost" });
type PostForm = z.infer<typeof postSchema>;
type WebMcpTool = { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute: (input: unknown) => unknown };
type WebMcpContext = { registerTool: (tool: WebMcpTool, options?: { signal?: AbortSignal }) => void | Promise<void> };

function LogoMark() { return <div className="brand-mark" aria-hidden="true"><span /><i /></div> }
function Pill({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "green" | "orange" | "purple" }) { return <span className={`pill ${tone}`}>{children}</span> }
function Avatar({ initials, color, size = "md" }: { initials: string; color: string; size?: "sm" | "md" | "lg" }) { return <span className={`team-avatar ${size}`} style={{ background: color }}>{initials}</span> }
function StatCard({ icon: Icon, label, value, trend }: { icon: React.ElementType; label: string; value: string; trend: string }) { return <div className="stat-card"><div className="stat-icon"><Icon /></div><div><p>{label}</p><strong>{value}</strong><span>{trend}</span></div></div> }
function PageHeader({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</div> }

function MatchCard({ post, onView }: { post: MatchPost; onView: () => void }) {
  return <article className="match-card"><div className="match-top"><div className="team-lockup"><Avatar initials={post.initials} color={post.color} /><div><h3>{post.team}</h3><p><ShieldCheck /> {post.rating} reliability</p></div></div><Pill tone={post.skill === "Advanced" ? "purple" : post.skill === "Beginner" ? "orange" : "green"}>{post.skill}</Pill></div><div className="match-ground"><MapPin /><div><strong>{post.ground}</strong><span>{post.area}, Hyderabad</span></div></div><div className="match-specs"><div><CalendarDays /><span><b>{post.date}</b>{post.time}</span></div><div><Target /><span><b>{post.overs} overs</b>{post.ball} ball</span></div></div><div className="match-bottom"><div><span>Opponent share</span><strong>₹{post.share.toLocaleString("en-IN")}</strong><small>of ₹{post.cost.toLocaleString("en-IN")}</small></div><Button onClick={onView} className="action-button">View match <ChevronRight /></Button></div><p className="post-age">Posted {post.age}</p></article>
}

export default function Home() {
  const [view, setView] = useState<View>("dashboard"); const [mobileNav, setMobileNav] = useState(false); const [selected, setSelected] = useState<MatchPost | null>(null); const [createOpen, setCreateOpen] = useState(false); const [requestOpen, setRequestOpen] = useState(false); const [requestSent, setRequestSent] = useState<number[]>([]); const [accepted, setAccepted] = useState(false); const [query, setQuery] = useState(""); const [area, setArea] = useState("All areas"); const [ballType, setBallType] = useState("All balls"); const [balls, setBalls] = useState<{ label: string; runs: number; legal: boolean; wicket?: boolean }[]>([]);
  const { register, handleSubmit, reset, formState: { errors } } = useForm<PostForm>({ resolver: zodResolver(postSchema), defaultValues: { team: "Banjara Blazers", overs: 20, ballType: "Tennis", skill: "Intermediate", cost: 5000, share: 2500 } });
  const filtered = posts.filter(p => `${p.team} ${p.ground} ${p.area}`.toLowerCase().includes(query.toLowerCase()) && (area === "All areas" || p.area === area) && (ballType === "All balls" || p.ball === ballType));
  const totalRuns = balls.reduce((s, b) => s + b.runs, 0), wickets = balls.filter(b => b.wicket).length, legalBalls = balls.filter(b => b.legal).length, overText = `${Math.floor(legalBalls / 6)}.${legalBalls % 6}`;
  const navigate = (next: View) => { setView(next); setMobileNav(false); window.scrollTo({ top: 0, behavior: "smooth" }) };
  const sendRequest = () => { if (!selected) return; setRequestSent(c => [...c, selected.id]); setRequestOpen(false); setSelected(null); toast.success("Match request sent", { description: "The host captain will be notified." }) };
  const submitPost = () => { setCreateOpen(false); reset(); toast.success("Match post is live", { description: "Teams can now find and challenge you." }) };
  const score = (label: string) => { const map: Record<string, { runs: number; legal: boolean; wicket?: boolean }> = { "0": { runs: 0, legal: true }, "1": { runs: 1, legal: true }, "2": { runs: 2, legal: true }, "3": { runs: 3, legal: true }, "4": { runs: 4, legal: true }, "6": { runs: 6, legal: true }, W: { runs: 0, legal: true, wicket: true }, WD: { runs: 1, legal: false }, NB: { runs: 1, legal: false }, BYE: { runs: 1, legal: true }, LB: { runs: 1, legal: true } }; setBalls(c => [...c, { label, ...map[label] }]) };
  useEffect(() => {
    const context = (document as Document & { modelContext?: WebMcpContext }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    const allowed = ["0", "1", "2", "3", "4", "6", "W", "WD", "NB", "BYE", "LB"];
    void Promise.resolve(context.registerTool({ name: "open_match_finder", title: "Find cricket matches", description: "Open the visible match finder to browse opponent posts in Hyderabad.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute: () => { setView("matches"); return { view: "matches", availableMatches: posts.length } } }, { signal: lifecycle.signal }));
    void Promise.resolve(context.registerTool({ name: "record_delivery", title: "Record a delivery", description: "Record one delivery in the open live scorecard and update the reconstructed score.", inputSchema: { type: "object", properties: { result: { type: "string", enum: allowed } }, required: ["result"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: (input) => { const result = typeof input === "object" && input && "result" in input ? String((input as { result: unknown }).result) : ""; if (!allowed.includes(result)) throw new Error("Invalid delivery result"); setView("scoring"); score(result); return { recorded: result } } }, { signal: lifecycle.signal }));
    return () => lifecycle.abort();
  }, []);
  return <div className="app-shell"><Toaster position="top-right" richColors />
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}><div className="brand"><LogoMark /><div><strong>CricketConnect</strong><span>Hyderabad</span></div></div><nav><p>PLAY</p>{nav.slice(0,4).map(item => <button key={item.id} onClick={() => navigate(item.id)} className={view === item.id ? "active" : ""}><item.icon /><span>{item.label}</span>{item.badge && <b>{item.badge}</b>}</button>)}<p>CLUBHOUSE</p>{nav.slice(4).map(item => <button key={item.id} onClick={() => navigate(item.id)} className={view === item.id ? "active" : ""}><item.icon /><span>{item.label}</span></button>)}</nav><div className="sidebar-card"><Sparkles /><strong>Make Sunday count.</strong><span>Three teams are looking near you.</span><button onClick={() => navigate("matches")}>Explore matches <ChevronRight /></button></div><div className="user-card"><span className="user-avatar">RV</span><div><strong>Rohan Varma</strong><small>Captain · Blazers</small></div><ChevronDown /></div></aside>
    <section className="main-area"><header className="topbar"><button className="menu-button" onClick={() => setMobileNav(!mobileNav)} aria-label="Toggle menu"><Menu /></button><div className="location"><MapPin /><span>Hyderabad</span><ChevronDown /></div><div className="top-actions"><button aria-label="Notifications"><Bell /><i /></button><Button onClick={() => setCreateOpen(true)} className="primary-cta"><Zap /> Post a match</Button></div></header><main>
      {view === "dashboard" && <Dashboard onNavigate={navigate} onCreate={() => setCreateOpen(true)} onView={setSelected} />}
      {view === "matches" && <FindMatches filtered={filtered} query={query} setQuery={setQuery} area={area} setArea={setArea} ballType={ballType} setBallType={setBallType} onView={setSelected} />}
      {view === "requests" && <Requests accepted={accepted} onAccept={() => { setAccepted(true); toast.success("Fixture confirmed", { description: "Falcon XI has been added to your fixtures." }) }} />}
      {view === "fixtures" && <Fixtures accepted={accepted} onScore={() => navigate("scoring")} />}{view === "teams" && <TeamProfile />}{view === "profile" && <PlayerProfile />}
      {view === "scoring" && <Scoring totalRuns={totalRuns} wickets={wickets} overText={overText} legalBalls={legalBalls} recentBalls={balls.slice(-12)} onScore={score} onUndo={() => setBalls(c => c.slice(0,-1))} />}
    </main></section>
    <Dialog open={Boolean(selected) && !requestOpen} onOpenChange={open => !open && setSelected(null)}><DialogContent className="match-dialog">{selected && <><DialogHeader><div className="dialog-team"><Avatar initials={selected.initials} color={selected.color} size="lg" /><div><Pill tone="green">Open challenge</Pill><DialogTitle>{selected.team} needs an opponent</DialogTitle></div></div><DialogDescription>{selected.note}</DialogDescription></DialogHeader><div className="dialog-detail-grid"><div><MapPin /><span>Ground</span><strong>{selected.ground}<small>{selected.area}, Hyderabad</small></strong></div><div><CalendarDays /><span>When</span><strong>{selected.date}<small>{selected.time}</small></strong></div><div><Target /><span>Format</span><strong>{selected.overs} overs<small>{selected.ball} ball</small></strong></div><div><CircleDollarSign /><span>Your share</span><strong>₹{selected.share.toLocaleString("en-IN")}<small>Total ₹{selected.cost.toLocaleString("en-IN")}</small></strong></div></div><div className="host-stats"><div><strong>{selected.played}</strong><span>Matches</span></div><div><strong>{selected.wins}</strong><span>Wins</span></div><div><strong>{selected.rating}</strong><span>Rating</span></div><div><strong>{selected.cancellations}</strong><span>Cancellations</span></div></div><DialogFooter><Button variant="outline" onClick={() => setSelected(null)}>Not now</Button><Button disabled={requestSent.includes(selected.id)} onClick={() => setRequestOpen(true)} className="action-button">{requestSent.includes(selected.id) ? <><Check /> Request sent</> : <>Request match <Swords /></>}</Button></DialogFooter></>}</DialogContent></Dialog>
    <Dialog open={requestOpen} onOpenChange={setRequestOpen}><DialogContent><DialogHeader><DialogTitle>Challenge {selected?.team}</DialogTitle><DialogDescription>Choose the team you’ll bring to this match.</DialogDescription></DialogHeader><label className="field"><span>Your team</span><select defaultValue="Banjara Blazers"><option>Banjara Blazers</option><option>Road No. 12 XI</option></select></label><label className="field"><span>Message <small>Optional</small></span><textarea defaultValue="We’re available and ready for a good game. Looking forward to it!" /></label><DialogFooter><Button variant="outline" onClick={() => setRequestOpen(false)}>Cancel</Button><Button className="action-button" onClick={sendRequest}>Send request <Swords /></Button></DialogFooter></DialogContent></Dialog>
    <CreatePostDialog open={createOpen} setOpen={setCreateOpen} register={register} errors={errors} onSubmit={handleSubmit(submitPost)} />
  </div>
}

function Dashboard({ onNavigate, onCreate, onView }: { onNavigate: (v: View) => void; onCreate: () => void; onView: (p: MatchPost) => void }) { return <div className="page dashboard-page"><section className="welcome"><div><p className="eyebrow">THURSDAY · 17 SEPTEMBER</p><h1>Good evening, Rohan.</h1><p>Your next match is in <strong>2 days.</strong> Time to lock in the playing XI.</p></div><div className="streak"><Flame /><span><b>4</b> match streak</span></div></section><div className="stats-grid"><StatCard icon={CalendarDays} label="Upcoming matches" value="03" trend="Next on Sunday" /><StatCard icon={Target} label="Open posts" value="01" trend="6 profile views" /><StatCard icon={Swords} label="Pending requests" value="02" trend="Needs your reply" /><StatCard icon={Trophy} label="Matches played" value="24" trend="Won 15 · 62.5%" /></div><div className="dashboard-grid"><section className="panel upcoming-panel"><div className="panel-title"><div><p className="eyebrow">NEXT UP</p><h2>Upcoming match</h2></div><button onClick={() => onNavigate("fixtures")}>All fixtures <ChevronRight /></button></div><div className="fixture-hero"><div className="date-tile"><span>SEP</span><strong>20</strong><small>SUN</small></div><div className="versus"><div><Avatar initials="BB" color="#11263d" size="lg" /><span>Banjara Blazers</span></div><b>VS</b><div><Avatar initials="CY" color="#ff7849" size="lg" /><span>Cyberabad XI</span></div></div><div className="fixture-info"><div><Clock3 /> 6:30 AM</div><div><MapPin /> Boundary Box Arena</div><div><Target /> 20 overs · Tennis</div></div><Button variant="outline" onClick={() => onNavigate("fixtures")}>View fixture</Button></div></section><section className="panel quick-panel"><div className="panel-title"><div><p className="eyebrow">SHORTCUTS</p><h2>Quick actions</h2></div></div><button onClick={() => onNavigate("matches")}><span><Search /></span><div><strong>Find an opponent</strong><small>12 matches available</small></div><ChevronRight /></button><button onClick={onCreate}><span><Zap /></span><div><strong>Post a match</strong><small>Share your ground slot</small></div><ChevronRight /></button><button onClick={() => onNavigate("teams")}><span><UsersRound /></span><div><strong>Manage team</strong><small>16 active players</small></div><ChevronRight /></button></section></div><section className="section-block"><div className="panel-title"><div><p className="eyebrow">NEAR YOU</p><h2>Teams looking for opponents</h2></div><button onClick={() => onNavigate("matches")}>View all <ChevronRight /></button></div><div className="cards-grid">{posts.slice(0,3).map(post => <MatchCard key={post.id} post={post} onView={() => onView(post)} />)}</div></section></div> }

function FindMatches({ filtered, query, setQuery, area, setArea, ballType, setBallType, onView }: { filtered: MatchPost[]; query: string; setQuery: (v:string)=>void; area:string; setArea:(v:string)=>void; ballType:string; setBallType:(v:string)=>void; onView:(p:MatchPost)=>void }) { return <div className="page"><PageHeader eyebrow="OPEN CHALLENGES" title="Find your next game" action={<span className="result-count">{filtered.length} matches available</span>} /><div className="filters"><label className="search-box"><Search /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search team, ground or area" /></label><select value={area} onChange={e => setArea(e.target.value)}><option>All areas</option><option>Gachibowli</option><option>Kondapur</option><option>Madhapur</option><option>Kompally</option></select><select value={ballType} onChange={e => setBallType(e.target.value)}><option>All balls</option><option>Tennis</option><option>Leather</option></select><select><option>Any skill</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><select><option>Newest first</option><option>Match date</option><option>Closest date</option></select></div><div className="cards-grid matches-list">{filtered.map(post => <MatchCard key={post.id} post={post} onView={() => onView(post)} />)}</div>{!filtered.length && <div className="empty-state"><Search /><h3>No matches found</h3><p>Try widening the area or ball type.</p></div>}</div> }

function Requests({ accepted, onAccept }: { accepted:boolean; onAccept:()=>void }) { return <div className="page"><PageHeader eyebrow="YOUR MATCH POST" title="Opponent requests" action={<Pill tone="orange">2 need a reply</Pill>} /><div className="request-context"><div><CalendarDays /><span><b>Sun, 27 Sep · 7:00 AM</b>Pitch Perfect, Madhapur · 20 overs</span></div><Pill tone="green">Open</Pill></div><div className="request-list"><RequestCard initials="FX" color="#3178f6" team="Falcon XI" played="31" won="19" cancelled="2" message="We play competitive tennis-ball cricket and can reach by 6:30. Happy to split the ground cost." accepted={accepted} onAccept={onAccept} /><RequestCard initials="RR" color="#8b5cf6" team="Raidurg Royals" played="47" won="28" cancelled="5" message="Full squad confirmed. We can arrange one umpire if needed." onAccept={() => toast.success("Fixture confirmed")} /></div></div> }
function RequestCard({ initials, color, team, played, won, cancelled, message, accepted, onAccept }: { initials:string;color:string;team:string;played:string;won:string;cancelled:string;message:string;accepted?:boolean;onAccept:()=>void }) { return <article className={`request-card ${accepted ? "accepted" : ""}`}><div className="request-team"><Avatar initials={initials} color={color} size="lg" /><div><h3>{team}</h3><p><Pill tone="green">Intermediate</Pill> <ShieldCheck /> 4.7 rating</p></div></div><div className="request-numbers"><span><b>{played}</b> played</span><span><b>{won}</b> won</span><span><b>{cancelled}</b> cancelled</span></div><blockquote>“{message}”</blockquote>{accepted ? <div className="accepted-label"><Check /> Accepted · Fixture created</div> : <div className="request-actions"><Button variant="outline" onClick={() => toast("Request declined")}>Decline</Button><Button className="action-button" onClick={onAccept}>Accept & create fixture <Check /></Button></div>}</article> }

function Fixtures({ accepted, onScore }: { accepted:boolean;onScore:()=>void }) { const fixtures = [{ date:"20", month:"SEP", opponent:"Cyberabad XI", initials:"CY", color:"#ff7849", ground:"Boundary Box Arena", time:"6:30 AM", status:"Confirmed" }, ...(accepted ? [{ date:"27", month:"SEP", opponent:"Falcon XI", initials:"FX", color:"#3178f6", ground:"Pitch Perfect", time:"7:00 AM", status:"Just confirmed" }] : [])]; return <div className="page"><PageHeader eyebrow="MATCH CENTRE" title="Your fixtures" /><div className="fixture-list">{fixtures.map(f => <article key={f.opponent}><div className="date-tile"><span>{f.month}</span><strong>{f.date}</strong><small>SUN</small></div><div className="fixture-team"><Avatar initials="BB" color="#11263d" /><span>vs</span><Avatar initials={f.initials} color={f.color} /><div><strong>Banjara Blazers vs {f.opponent}</strong><small><MapPin /> {f.ground} · {f.time}</small></div></div><Pill tone="green">{f.status}</Pill><Button onClick={onScore} variant="outline">Open scorecard <ChevronRight /></Button></article>)}</div></div> }

function TeamProfile() { return <div className="page"><PageHeader eyebrow="YOUR CLUBHOUSE" title="Banjara Blazers" action={<Button variant="outline">Edit team</Button>} /><section className="team-banner"><div className="team-title"><Avatar initials="BB" color="#11263d" size="lg" /><div><Pill tone="green">Intermediate · Tennis</Pill><h2>Banjara Blazers</h2><p><MapPin /> Banjara Hills, Hyderabad</p></div></div><p>Weekend cricket, properly organized. Competitive on the field and dependable off it.</p></section><div className="stats-grid team-stats"><StatCard icon={Target} label="Matches" value="24" trend="22 completed" /><StatCard icon={Trophy} label="Wins" value="15" trend="62.5% win rate" /><StatCard icon={ShieldCheck} label="Reliability" value="96%" trend="1 cancellation" /><StatCard icon={Sparkles} label="Team rating" value="4.8" trend="Across 18 ratings" /></div><section className="panel roster"><div className="panel-title"><div><p className="eyebrow">PLAYERS</p><h2>Squad · 16</h2></div><Button size="sm">Add player</Button></div>{[["RV","Rohan Varma","Captain · All-rounder","#11263d"],["AK","Arjun Kumar","Batsman","#ff7849"],["SM","Sai Mehta","Wicket-keeper","#199d6d"],["VN","Vikram Naidu","Bowler","#8b5cf6"]].map(([i,n,r,c]) => <div className="player-row" key={n}><Avatar initials={i} color={c} /><div><strong>{n}</strong><span>{r}</span></div><span className="availability"><i /> Available</span><ChevronRight /></div>)}</section></div> }
function PlayerProfile() { return <div className="page"><PageHeader eyebrow="PLAYER PROFILE" title="Your cricket card" action={<Button variant="outline">Edit profile</Button>} /><section className="profile-hero"><div className="profile-avatar">RV<span>#18</span></div><div><Pill tone="orange">Captain</Pill><h2>Rohan Varma</h2><p>Right-handed · Right-arm medium · All-rounder</p><div><span><UsersRound /> Banjara Blazers</span><span><MapPin /> Banjara Hills</span></div></div><aside><strong>4.8</strong><span>Player rating</span><small>Top 12% in Hyderabad</small></aside></section><div className="career-grid"><Career title="CAREER BATTING" value="1,248 runs" icon={Target} stats={[["24","Matches"],["22","Innings"],["68*","High score"],["34.7","Average"],["142.6","Strike rate"],["8 / 1","50s / 100s"]]} /><Career title="CAREER BOWLING" value="31 wickets" icon={Gauge} stats={[["82.3","Overs"],["6.8","Economy"],["4/18","Best bowling"],["2","4-wicket hauls"],["18","Catches"],["2","Stumpings"]]} /></div></div> }
function Career({ title, value, icon:Icon, stats }: { title:string;value:string;icon:React.ElementType;stats:string[][] }) { return <section className="career-card"><div className="career-heading"><span><Icon /></span><div><p className="eyebrow">{title}</p><h2>{value}</h2></div></div><div className="metric-grid">{stats.map(([v,l]) => <span key={l}><b>{v}</b>{l}</span>)}</div></section> }

function Scoring({ totalRuns, wickets, overText, legalBalls, recentBalls, onScore, onUndo }: { totalRuns:number;wickets:number;overText:string;legalBalls:number;recentBalls:{label:string;runs:number;legal:boolean;wicket?:boolean}[];onScore:(l:string)=>void;onUndo:()=>void }) { return <div className="page scoring-page"><PageHeader eyebrow="LIVE SCORING" title="Banjara Blazers batting" action={<Pill tone="orange"><i className="live-dot" /> Live</Pill>} /><section className="scoreboard"><div className="score-main"><span>SCORE</span><strong>{totalRuns}<small>/{wickets}</small></strong><p>{overText} / 20 overs</p></div><div className="score-target"><span>FIRST INNINGS</span><b>Projected {Math.round(totalRuns / Math.max(legalBalls,1) * 120)}</b><small>Current RR {(totalRuns / Math.max(legalBalls,1) * 6).toFixed(2)}</small></div><div className="ball-strip">{recentBalls.length ? recentBalls.map((ball,i) => <span className={ball.wicket ? "wicket" : ball.runs >= 4 ? "boundary" : ""} key={`${ball.label}-${i}`}>{ball.label}</span>) : <em>Tap a scoring button to begin this over</em>}</div></section><div className="scoring-grid"><section className="panel batters"><div className="panel-title"><div><p className="eyebrow">AT THE CREASE</p><h2>Batters</h2></div></div><div className="batter-row active"><span>*</span><div><strong>Rohan Varma</strong><small>Right-handed</small></div><b>{Math.max(0,totalRuns-12)}</b><span>{Math.max(1,legalBalls-5)} balls</span><strong>{totalRuns ? "142.8" : "0.0"} SR</strong></div><div className="batter-row"><span /><div><strong>Arjun Kumar</strong><small>Right-handed</small></div><b>12</b><span>9 balls</span><strong>133.3 SR</strong></div><div className="bowler-row"><Avatar initials="VN" color="#8b5cf6" size="sm" /><div><span>Current bowler</span><strong>Vikram Naidu</strong></div><b>{overText}</b><span>{Math.max(totalRuns-5,0)} runs</span><strong>{wickets} wkts</strong></div></section><section className="panel scoring-pad"><div className="panel-title"><div><p className="eyebrow">THIS DELIVERY</p><h2>Add score</h2></div><Button variant="ghost" onClick={onUndo}><Undo2 /> Undo</Button></div><div className="run-buttons">{["0","1","2","3","4","6"].map(l => <button key={l} onClick={() => onScore(l)} className={l === "4" || l === "6" ? "boundary" : ""}>{l}</button>)}</div><div className="event-buttons"><button className="wicket" onClick={() => onScore("W")}>WICKET</button>{["WD","NB","BYE","LB"].map(l => <button key={l} onClick={() => onScore(l)}>{l === "LB" ? "LEG BYE" : l}</button>)}</div><p className="scoring-note"><ShieldCheck /> Every action is saved as a ball record. The score is reconstructed from this event history.</p></section></div></div> }

function CreatePostDialog({ open, setOpen, register, errors, onSubmit }: { open:boolean;setOpen:(v:boolean)=>void;register:ReturnType<typeof useForm<PostForm>>["register"];errors:ReturnType<typeof useForm<PostForm>>["formState"]["errors"];onSubmit:React.FormEventHandler<HTMLFormElement> }) { return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="create-dialog"><DialogHeader><DialogTitle>Post an opponent challenge</DialogTitle><DialogDescription>Share your confirmed ground slot with teams across Hyderabad.</DialogDescription></DialogHeader><form onSubmit={onSubmit}><div className="form-grid"><label className="field full"><span>Hosting team</span><select {...register("team")}><option>Banjara Blazers</option><option>Road No. 12 XI</option></select></label><Field label="Match date" error={errors.date?.message}><Input type="date" {...register("date")} /></Field><Field label="Area" error={errors.area?.message}><Input placeholder="e.g. Gachibowli" {...register("area")} /></Field><Field label="Start time" error={errors.startTime?.message}><Input type="time" {...register("startTime")} /></Field><Field label="End time" error={errors.endTime?.message}><Input type="time" {...register("endTime")} /></Field><label className="field full"><span>Ground</span><Input placeholder="Search or enter a custom ground" {...register("ground")} />{errors.ground && <em>{errors.ground.message}</em>}</label><label className="field"><span>Overs</span><select {...register("overs")}><option>10</option><option>15</option><option>20</option><option>25</option><option>30</option></select></label><label className="field"><span>Ball type</span><select {...register("ballType")}><option>Tennis</option><option>Leather</option></select></label><label className="field"><span>Skill level</span><select {...register("skill")}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><Field label="Total ground cost"><Input type="number" {...register("cost")} /></Field><Field label="Opponent contribution" error={errors.share?.message}><Input type="number" {...register("share")} /></Field><label className="field full"><span>Notes <small>Optional</small></span><textarea placeholder="Anything the opponent should know?" {...register("notes")} /></label></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" className="action-button">Publish post <Zap /></Button></DialogFooter></form></DialogContent></Dialog> }
function Field({ label, error, children }: { label:string;error?:string;children:React.ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <em>{error}</em>}</label> }
